ktor:
  application:
    modules:
      - com.sambutcher.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
typedb:
  address: "localhost:1729"
  database: "dnd"
