ktor:
  application:
    modules:
      - com.sambutcher.ApplicationKt.module
  deployment:
    port: 8080
typedb:
  address: "https://n69m16-0.cluster.typedb.com:80"
  database: "sam-hackathon"
  username: "admin"
  password: ${TYPEDB_PASSWORD:password}
  tlsEnabled: True
